<a href="https://colab.research.google.com/github/HarisJafri-xcode/Data-Analyst-in-Python/blob/main/Data-Manipulation-with-Pandas/Slicing_and_Indexing_DataFrame.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Explicit Indexes

In [ ]:
# Loading Important Data Science Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
# Storing file path
file_path = "https://raw.githubusercontent.com/HarisJafri-xcode/Python-Session-DataSets/refs/heads/main/Data_Manipulation/temperatures.csv"

In [ ]:
# Loading Dataset into a DataFrame
temperatures = pd.read_csv(file_path)

In [ ]:
# Observing first 5 Rows of the Data Frame
temperatures.head()

       date     city        country  avg_temp_c
0  1/1/2000  Abidjan  Côte D'Ivoire      27.293
1  2/1/2000  Abidjan  Côte D'Ivoire      27.685
2  3/1/2000  Abidjan  Côte D'Ivoire      29.061
3  4/1/2000  Abidjan  Côte D'Ivoire      28.162
4  5/1/2000  Abidjan  Côte D'Ivoire      27.547

In [ ]:
# Observing bottom 5 Rows of the Data Frame
temperatures.tail()

           date  city country  avg_temp_c
16495  5/1/2013  Xian   China      18.979
16496  6/1/2013  Xian   China      23.522
16497  7/1/2013  Xian   China      25.251
16498  8/1/2013  Xian   China      24.528
16499  9/1/2013  Xian   China         NaN

In [ ]:
# Extracting Information about Data Frame
temperatures.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16500 entries, 0 to 16499
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        16500 non-null  object
 1   city        16500 non-null  object
 2   country     16500 non-null  object
 3   avg_temp_c  16407 non-null  float64
dtypes: float64(1), object(3)
memory usage: 515.8+ KB

In [ ]:
# Converting date column to datetime object
temperatures['date'] = pd.to_datetime(temperatures['date'],format='%d/%m/%Y')

In [ ]:
# Setting 'city' as Index
temperatures_ind = temperatures.set_index('city')
temperatures_ind.head()

              date        country  avg_temp_c
city
Abidjan 2000-01-01  Côte D'Ivoire      27.293
Abidjan 2000-01-02  Côte D'Ivoire      27.685
Abidjan 2000-01-03  Côte D'Ivoire      29.061
Abidjan 2000-01-04  Côte D'Ivoire      28.162
Abidjan 2000-01-05  Côte D'Ivoire      27.547

In [ ]:
# Resetting Index without Deleting the Column
temperatures_ind.reset_index()

          city       date        country  avg_temp_c
0      Abidjan 2000-01-01  Côte D'Ivoire      27.293
1      Abidjan 2000-01-02  Côte D'Ivoire      27.685
2      Abidjan 2000-01-03  Côte D'Ivoire      29.061
3      Abidjan 2000-01-04  Côte D'Ivoire      28.162
4      Abidjan 2000-01-05  Côte D'Ivoire      27.547
...        ...        ...            ...         ...
16495     Xian 2013-01-05          China      18.979
16496     Xian 2013-01-06          China      23.522
16497     Xian 2013-01-07          China      25.251
16498     Xian 2013-01-08          China      24.528
16499     Xian 2013-01-09          China         NaN

[16500 rows x 4 columns]

In [ ]:
# Resetting Index after Deleting the Column
temperatures_ind.reset_index(drop=True)

            date        country  avg_temp_c
0     2000-01-01  Côte D'Ivoire      27.293
1     2000-01-02  Côte D'Ivoire      27.685
2     2000-01-03  Côte D'Ivoire      29.061
3     2000-01-04  Côte D'Ivoire      28.162
4     2000-01-05  Côte D'Ivoire      27.547
...          ...            ...         ...
16495 2013-01-05          China      18.979
16496 2013-01-06          China      23.522
16497 2013-01-07          China      25.251
16498 2013-01-08          China      24.528
16499 2013-01-09          China         NaN

[16500 rows x 3 columns]

In [ ]:
# Sorting Dataframe by Index in Descending Order
temperatures_ind.sort_index(ascending=False)

              date        country  avg_temp_c
city
Xian    2013-01-09          China         NaN
Xian    2005-01-02          China      -0.232
Xian    2004-01-12          China       0.190
Xian    2004-01-11          China       5.720
Xian    2004-01-10          China      11.229
...            ...            ...         ...
Abidjan 2009-01-03  Côte D'Ivoire      28.805
Abidjan 2009-01-02  Côte D'Ivoire      28.224
Abidjan 2009-01-01  Côte D'Ivoire      26.912
Abidjan 2008-01-12  Côte D'Ivoire      27.472
Abidjan 2000-01-01  Côte D'Ivoire      27.293

[16500 rows x 3 columns]

# .loc vs .iloc

In [ ]:
# Label based Subsetting
temperatures_ind.loc["Xian",["date","country"]]

           date country
city
Xian 2000-01-01   China
Xian 2000-01-02   China
Xian 2000-01-03   China
Xian 2000-01-04   China
Xian 2000-01-05   China
...         ...     ...
Xian 2013-01-05   China
Xian 2013-01-06   China
Xian 2013-01-07   China
Xian 2013-01-08   China
Xian 2013-01-09   China

[165 rows x 2 columns]

In [ ]:
# Index based Subsetting
temperatures_ind.iloc[-165:,0:2]

           date country
city
Xian 2000-01-01   China
Xian 2000-01-02   China
Xian 2000-01-03   China
Xian 2000-01-04   China
Xian 2000-01-05   China
...         ...     ...
Xian 2013-01-05   China
Xian 2013-01-06   China
Xian 2013-01-07   China
Xian 2013-01-08   China
Xian 2013-01-09   China

[165 rows x 2 columns]