<a href="https://colab.research.google.com/github/HarisJafri-xcode/Data-Analyst-in-Python/blob/main/Data-Manipulation-with-Pandas/Transforming_Data_Frame.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introducing Dataframe

In [ ]:
# Loading Important Data Science Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
# Storing file path
file_path = "https://raw.githubusercontent.com/HarisJafri-xcode/Python-Session-DataSets/refs/heads/main/Data_Manipulation/homelessness.csv"

In [ ]:
# Loading Dataset into a DataFrame
homelessness = pd.read_csv(file_path)

In [ ]:
# Observing first 5 Rows of the Data Frame
homelessness.head()

               region       state  individuals  family_members  state_pop
0  East South Central     Alabama         2570             864    4887681
1             Pacific      Alaska         1434             582     735139
2            Mountain     Arizona         7259            2606    7158024
3  West South Central    Arkansas         2280             432    3009733
4             Pacific  California       109008           20964   39461588

In [ ]:
# Observing bottom 5 Rows of the Data Frame
homelessness.tail()

                region          state  individuals  family_members  state_pop
46      South Atlantic       Virginia         3928            2047    8501286
47             Pacific     Washington        16424            5880    7523869
48      South Atlantic  West Virginia         1021             222    1804291
49  East North Central      Wisconsin         2740            2167    5807406
50            Mountain        Wyoming          434             205     577601

In [ ]:
# Extracting Information about Data Frame
homelessness.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   region          51 non-null     object
 1   state           51 non-null     object
 2   individuals     51 non-null     int64
 3   family_members  51 non-null     int64
 4   state_pop       51 non-null     int64
dtypes: int64(3), object(2)
memory usage: 2.1+ KB

In [ ]:
# How Many Number of Rows and Columns
homelessness.shape

(51, 5)

In [ ]:
# Display Summary Statistic for each Numeric Column
homelessness.describe().T

,count,mean,std,min,25%,50%,75%,max
individuals,51.0,7.225784e+03,1.599103e+04,434.0,1446.5,3082.0,6781.5,109008.0
family_members,51.0,3.504882e+03,7.805412e+03,75.0,592.0,1482.0,3196.0,52070.0
state_pop,51.0,6.405637e+06,7.327258e+06,577601.0,1777413.5,4461153.0,7340946.5,39461588.0

In [ ]:
# Show Pandas DF as 2D NumPy Array
homelessness.values

array([['East South Central', 'Alabama', 2570, 864, 4887681],
       ['Pacific', 'Alaska', 1434, 582, 735139],
       ['Mountain', 'Arizona', 7259, 2606, 7158024],
       ['West South Central', 'Arkansas', 2280, 432, 3009733],
       ['Pacific', 'California', 109008, 20964, 39461588],
       ['Mountain', 'Colorado', 7607, 3250, 5691287],
       ['New England', 'Connecticut', 2280, 1696, 3571520],
       ['South Atlantic', 'Delaware', 708, 374, 965479],
       ['South Atlantic', 'District of Columbia', 3770, 3134, 701547],
       ['South Atlantic', 'Florida', 21443, 9587, 21244317],
       ['South Atlantic', 'Georgia', 6943, 2556, 10511131],
       ['Pacific', 'Hawaii', 4131, 2399, 1420593],
       ['Mountain', 'Idaho', 1297, 715, 1750536],
       ['East North Central', 'Illinois', 6752, 3891, 12723071],
       ['East North Central', 'Indiana', 3776, 1482, 6695497],
       ['West North Central', 'Iowa', 1711, 1038, 3148618],
       ['West North Central', 'Kansas', 1443, 773, 2911359],
       ['East South Central', 'Kentucky', 2735, 953, 4461153],
       ['West South Central', 'Louisiana', 2540, 519, 4659690],
       ['New England', 'Maine', 1450, 1066, 1339057],
       ['South Atlantic', 'Maryland', 4914, 2230, 6035802],
       ['New England', 'Massachusetts', 6811, 13257, 6882635],
       ['East North Central', 'Michigan', 5209, 3142, 9984072],
       ['West North Central', 'Minnesota', 3993, 3250, 5606249],
       ['East South Central', 'Mississippi', 1024, 328, 2981020],
       ['West North Central', 'Missouri', 3776, 2107, 6121623],
       ['Mountain', 'Montana', 983, 422, 1060665],
       ['West North Central', 'Nebraska', 1745, 676, 1925614],
       ['Mountain', 'Nevada', 7058, 486, 3027341],
       ['New England', 'New Hampshire', 835, 615, 1353465],
       ['Mid-Atlantic', 'New Jersey', 6048, 3350, 8886025],
       ['Mountain', 'New Mexico', 1949, 602, 2092741],
       ['Mid-Atlantic', 'New York', 39827, 52070, 19530351],
       ['South Atlantic', 'North Carolina', 6451, 2817, 10381615],
       ['West North Central', 'North Dakota', 467, 75, 758080],
       ['East North Central', 'Ohio', 6929, 3320, 11676341],
       ['West South Central', 'Oklahoma', 2823, 1048, 3940235],
       ['Pacific', 'Oregon', 11139, 3337, 4181886],
       ['Mid-Atlantic', 'Pennsylvania', 8163, 5349, 12800922],
       ['New England', 'Rhode Island', 747, 354, 1058287],
       ['South Atlantic', 'South Carolina', 3082, 851, 5084156],
       ['West North Central', 'South Dakota', 836, 323, 878698],
       ['East South Central', 'Tennessee', 6139, 1744, 6771631],
       ['West South Central', 'Texas', 19199, 6111, 28628666],
       ['Mountain', 'Utah', 1904, 972, 3153550],
       ['New England', 'Vermont', 780, 511, 624358],
       ['South Atlantic', 'Virginia', 3928, 2047, 8501286],
       ['Pacific', 'Washington', 16424, 5880, 7523869],
       ['South Atlantic', 'West Virginia', 1021, 222, 1804291],
       ['East North Central', 'Wisconsin', 2740, 2167, 5807406],
       ['Mountain', 'Wyoming', 434, 205, 577601]], dtype=object)

In [ ]:
# Show Column Names
homelessness.columns

Index(['region', 'state', 'individuals', 'family_members', 'state_pop'], dtype='object')

In [ ]:
# Show Index for the Rows
homelessness.index

RangeIndex(start=0, stop=51, step=1)

# Sorting and Subsetting Dataframe

In [ ]:
# Sorting Data Frame based on "individuals"
homelessness_ind = homelessness.sort_values('individuals')
homelessness_ind.head()

                region         state  individuals  family_members  state_pop
50            Mountain       Wyoming          434             205     577601
34  West North Central  North Dakota          467              75     758080
7       South Atlantic      Delaware          708             374     965479
39         New England  Rhode Island          747             354    1058287
45         New England       Vermont          780             511     624358

In [ ]:
# Sorting Data Frame based on "family_members" based on descending order
homelessness_fam = homelessness.sort_values('family_members',ascending=False)
homelessness_fam.head()

                region          state  individuals  family_members  state_pop
32        Mid-Atlantic       New York        39827           52070   19530351
4              Pacific     California       109008           20964   39461588
21         New England  Massachusetts         6811           13257    6882635
9       South Atlantic        Florida        21443            9587   21244317
43  West South Central          Texas        19199            6111   28628666

In [ ]:
# Sorting on Multiple Columns
homelessness_reg_fam = homelessness.sort_values(['region','family_members'],ascending=[True,False])
homelessness_reg_fam.head()

                region      state  individuals  family_members  state_pop
13  East North Central   Illinois         6752            3891   12723071
35  East North Central       Ohio         6929            3320   11676341
22  East North Central   Michigan         5209            3142    9984072
49  East North Central  Wisconsin         2740            2167    5807406
14  East North Central    Indiana         3776            1482    6695497

In [ ]:
# Displaying Top 5 Rows of Column Data Series
homelessness['individuals'].head()

0      2570
1      1434
2      7259
3      2280
4    109008
Name: individuals, dtype: int64

In [ ]:
# Storing the Data Series inside a Variable
individuals = homelessness['individuals']
individuals.head()

0      2570
1      1434
2      7259
3      2280
4    109008
Name: individuals, dtype: int64

In [ ]:
# Extracting DataFrame from Data Frame
state_fam = homelessness[['state','family_members']]
state_fam.head()

        state  family_members
0     Alabama             864
1      Alaska             582
2     Arizona            2606
3    Arkansas             432
4  California           20964

In [ ]:
# Extracting DataFrame from Data Frame
ind_state = homelessness[['individuals','state']]
ind_state.head()

   individuals       state
0         2570     Alabama
1         1434      Alaska
2         7259     Arizona
3         2280    Arkansas
4       109008  California

In [ ]:
# Constructing Mask and use it to Subset Data Frame
ind_gt_10k_mask = homelessness['individuals'] > 10000
ind_gt_10k = homelessness[ind_gt_10k_mask]
ind_gt_10k

                region       state  individuals  family_members  state_pop
4              Pacific  California       109008           20964   39461588
9       South Atlantic     Florida        21443            9587   21244317
32        Mid-Atlantic    New York        39827           52070   19530351
37             Pacific      Oregon        11139            3337    4181886
43  West South Central       Texas        19199            6111   28628666
47             Pacific  Washington        16424            5880    7523869

In [ ]:
# Constructing Mask and use it to Subset Data Frame
mountain_reg_mask = (homelessness['region'] == 'Mountain')
mountain_reg = homelessness[mountain_reg_mask]
mountain_reg

      region       state  individuals  family_members  state_pop
2   Mountain     Arizona         7259            2606    7158024
5   Mountain    Colorado         7607            3250    5691287
12  Mountain       Idaho         1297             715    1750536
26  Mountain     Montana          983             422    1060665
28  Mountain      Nevada         7058             486    3027341
31  Mountain  New Mexico         1949             602    2092741
44  Mountain        Utah         1904             972    3153550
50  Mountain     Wyoming          434             205     577601

In [ ]:
# Constructing Multiple Masks
fam_lt_1k_pac_condition_1 = homelessness['family_members'] < 1000
fam_lt_1k_pac_condition_2 = homelessness['region'] == "Pacific"

In [ ]:
# Passing Mask to filter rows that comply both conditions
fam_lt_1k_pac = homelessness[fam_lt_1k_pac_condition_1 & fam_lt_1k_pac_condition_2]
fam_lt_1k_pac

    region   state  individuals  family_members  state_pop
1  Pacific  Alaska         1434             582     735139

In [ ]:
# Subsetting Rows by Categorical Variables
important_states = ["California", "Arizona", "Nevada", "Utah"]

# Creating Mask
mask_important_states = homelessness['state'].isin(important_states)

# Filter for rows
important_states_homelessness = homelessness[mask_important_states]

# Display those important states
important_states_homelessness

      region       state  individuals  family_members  state_pop
2   Mountain     Arizona         7259            2606    7158024
4    Pacific  California       109008           20964   39461588
28  Mountain      Nevada         7058             486    3027341
44  Mountain        Utah         1904             972    3153550

# New Columns

In [ ]:
# Add total col as sum of individuals and family_members
homelessness['total'] = homelessness['individuals'] + homelessness['family_members']

# display homelessness
homelessness.head()

,region,state,individuals,family_members,state_pop,total
0,East South Central,Alabama,2570,864,4887681,3434
1,Pacific,Alaska,1434,582,735139,2016
2,Mountain,Arizona,7259,2606,7158024,9865
3,West South Central,Arkansas,2280,432,3009733,2712
4,Pacific,California,109008,20964,39461588,129972

In [ ]:
# Add p_homeless col as proportion of total homeless population to the state population
homelessness['p_homeless'] = (homelessness['total']/homelessness['state_pop'])*100

# display homelessness
homelessness.head()

,region,state,individuals,family_members,state_pop,total,p_homeless
0,East South Central,Alabama,2570,864,4887681,3434,0.070258
1,Pacific,Alaska,1434,582,735139,2016,0.274234
2,Mountain,Arizona,7259,2606,7158024,9865,0.137817
3,West South Central,Arkansas,2280,432,3009733,2712,0.090108
4,Pacific,California,109008,20964,39461588,129972,0.329363

Which state has the highest number of homeless individuals per 10,000 people in the state?

In [ ]:
# Creating a New Column to find how many homeless people are there for every 10,000 people in each state
homelessness["indiv_per_10k"] = 10000 * (homelessness['individuals'] / homelessness['state_pop'] )

# Display Dataframe
homelessness.head()

,region,state,individuals,family_members,state_pop,total,p_homeless,indiv_per_10k
0,East South Central,Alabama,2570,864,4887681,3434,0.070258,5.258117
1,Pacific,Alaska,1434,582,735139,2016,0.274234,19.506515
2,Mountain,Arizona,7259,2606,7158024,9865,0.137817,10.141067
3,West South Central,Arkansas,2280,432,3009733,2712,0.090108,7.575423
4,Pacific,California,109008,20964,39461588,129972,0.329363,27.623825

In [ ]:
# Sort the Dataframe with respect to indiv_per_10k Column in ascending order and storing it
homelessness_srt = homelessness.sort_values('indiv_per_10k',ascending=False)

In [ ]:
# Displaying Sorted Data
homelessness_srt.head()

,region,state,individuals,family_members,state_pop,total,p_homeless,indiv_per_10k
8,South Atlantic,District of Columbia,3770,3134,701547,6904,0.984111,53.738381
11,Pacific,Hawaii,4131,2399,1420593,6530,0.459667,29.079406
4,Pacific,California,109008,20964,39461588,129972,0.329363,27.623825
37,Pacific,Oregon,11139,3337,4181886,14476,0.346160,26.636307
28,Mountain,Nevada,7058,486,3027341,7544,0.249196,23.314189