<a href="https://colab.research.google.com/github/HarisJafri-xcode/Data-Analyst-in-Python/blob/main/Intermediate-Python/Dictionaries_%26_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Dictionaries

In [ ]:
marks = [77, 83, 59, 39, 45, 91]
student = ["Alex", "Anand", "Bilal", "Zain", "Jacob", "Betty"]

In [ ]:
student.index("Bilal")

2

In [ ]:
marks[2]

59

In [ ]:
# Constructing Dictionary
student_marks = {"Alex": 77, "Anand": 83, "Bilal": 59, "Zain": 39, "Jacob": 45, "Betty": 91}

In [ ]:
# Extract Value of Key "Bilal"
student_marks["Bilal"]

59

In [ ]:
# Constructing Dictionary
age = {"Nina":12, "Fazal":23}
print(age)

{'Nina': 12, 'Fazal': 23}

In [ ]:
# Adding Nina again
age = {"Nina":12, "Fazal":23, "Nina":15}
print(age)

{'Nina': 15, 'Fazal': 23}

In [ ]:
# Constructing Awkward Dictionary
x = {True:"Hi", "1":"59", 2.49:False}
print(x)

{True: 'Hi', '1': '59', 2.49: False}

In [ ]:
# Using Wrong Key as Data Type
# y = {[1]:True, [2]:False} <---- Throws an Error
# print(y)

In [ ]:
# Constructing Dictionary
student_marks = {"Alex": 77, "Anand": 83, "Bilal": 59, "Zain": 39, "Jacob": 45, "Betty": 91}

In [ ]:
# Adding Vinod Marks
student_marks["Vinod"] = 89
print(student_marks)

{'Alex': 77, 'Anand': 83, 'Bilal': 59, 'Zain': 39, 'Jacob': 45, 'Betty': 91, 'Vinod': 89}

In [ ]:
# Updating Zain Marks
student_marks["Zain"] = 49
print(student_marks)

{'Alex': 77, 'Anand': 83, 'Bilal': 59, 'Zain': 49, 'Jacob': 45, 'Betty': 91, 'Vinod': 89}

In [ ]:
# Constructing Dictionary
student_marks = {"Alex": 77, "Anand": 83, "Bilal": 59, "Zain": 39, "Jacob": 45, "Betty": 91}

In [ ]:
# Deleting Alex
del student_marks["Alex"]
print(student_marks)

{'Anand': 83, 'Bilal': 59, 'Zain': 39, 'Jacob': 45, 'Betty': 91}

In [ ]:
# Opening Directory of students_marks
print(dir(student_marks))

['__class__', '__class_getitem__', '__contains__', '__delattr__', '__delitem__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__ior__', '__iter__', '__le__', '__len__', '__lt__', '__ne__', '__new__', '__or__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__ror__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', 'clear', 'copy', 'fromkeys', 'get', 'items', 'keys', 'pop', 'popitem', 'setdefault', 'update', 'values']

In [ ]:
# What does .clear Method do with a Dictionary
help(student_marks.clear)

Help on built-in function clear:

clear() method of builtins.dict instance
    Remove all items from the dict.

# Pandas

In [ ]:
# importing pandas
import pandas as pd

In [ ]:
# Predefined lists
names = ['United States', 'Australia', 'Japan', 'India', 'Russia', 'Morocco', 'Egypt']
drives_right =  [True, False, False, False, True, True, True]
cars_per_cap = [809, 731, 588, 18, 200, 70, 45]

In [ ]:
# Create dictionary cars_dict with three key:value pairs
# Keys are "String" and Column Heading
# Values are "Lists" and Column Content
cars_dict = {'country':names,'drives_right':drives_right,'cars_per_cap':cars_per_cap}

In [ ]:
print(cars_dict)

{'country': ['United States', 'Australia', 'Japan', 'India', 'Russia', 'Morocco', 'Egypt'], 'drives_right': [True, False, False, False, True, True, True], 'cars_per_cap': [809, 731, 588, 18, 200, 70, 45]}

In [ ]:
cars_df = pd.DataFrame(cars_dict)

In [ ]:
cars_df

         country  drives_right  cars_per_cap
0  United States          True           809
1      Australia         False           731
2          Japan         False           588
3          India         False            18
4         Russia          True           200
5        Morocco          True            70
6          Egypt          True            45

In [ ]:
print(cars_df)

         country  drives_right  cars_per_cap
0  United States          True           809
1      Australia         False           731
2          Japan         False           588
3          India         False            18
4         Russia          True           200
5        Morocco          True            70
6          Egypt          True            45

In [ ]:
# Loading DataFrame from CSV
cars_df = pd.read_csv('https://raw.githubusercontent.com/HarisJafri-xcode/Python-Session-DataSets/refs/heads/main/Intermediate_Python/cars.csv')

In [ ]:
cars_df

         country  drives_right  cars_per_cap
0  United States          True           809
1      Australia         False           731
2          Japan         False           588
3          India         False            18
4         Russia          True           200
5        Morocco          True            70
6          Egypt          True            45

In [ ]:
# Extracting 1 Column
cars_df["country"]

0    United States
1        Australia
2            Japan
3            India
4           Russia
5          Morocco
6            Egypt
Name: country, dtype: object

In [ ]:
# Extracting 2 Column
cars_df[["country","drives_right"]]

         country  drives_right
0  United States          True
1      Australia         False
2          Japan         False
3          India         False
4         Russia          True
5        Morocco          True
6          Egypt          True

In [ ]:
# Extracting all 3 Column
cars_df[["country","drives_right","cars_per_cap"]]

         country  drives_right  cars_per_cap
0  United States          True           809
1      Australia         False           731
2          Japan         False           588
3          India         False            18
4         Russia          True           200
5        Morocco          True            70
6          Egypt          True            45

In [ ]:
# Extracting Row Index 0
cars_df.iloc[0]

country         United States
drives_right             True
cars_per_cap              809
Name: 0, dtype: object

In [ ]:
# Extracting Row Index 0 to Index 2
cars_df.iloc[0:3]

         country  drives_right  cars_per_cap
0  United States          True           809
1      Australia         False           731
2          Japan         False           588

In [ ]:
# Extracting first two rows of last two columns
cars_df[["drives_right","cars_per_cap"]].iloc[0:2]

   drives_right  cars_per_cap
0          True           809
1         False           731

In [ ]:
# Extracting last three rows of 1st Column
cars_df["country"].iloc[-3:]

4     Russia
5    Morocco
6      Egypt
Name: country, dtype: object

In [ ]:
cars_df.loc[0:2]

         country  drives_right  cars_per_cap
0  United States          True           809
1      Australia         False           731
2          Japan         False           588