<a href="https://colab.research.google.com/github/HarisJafri-xcode/Data-Analyst-in-Python/blob/main/Intermediate-Python/Logic_Control_Flow_%26_Filtering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Comparison Operators

In [ ]:
# (15/5) is equal to 3 ?
print((15/5) == 3)

True

In [ ]:
# (15/3) is not equal to 5 ?
print((15/3) != 5)

False

In [ ]:
# Comparison of booleans
print(True == False)

False

In [ ]:
# Comparison of integers
print((-5*15) != 75)

True

In [ ]:
# Compare a boolean with an integer
print(True == 1)

True

In [ ]:
# Comparison of integers
x = -3 * 6
print(x >= -10)

False

In [ ]:
# Comparison of strings
y = "test"
print("test" <= y)

True

In [ ]:
# Comparison of booleans
print(True > False)

True

In [ ]:
# Create arrays
import numpy as np
my_house = np.array([18.0, 20.0, 10.75, 9.50])
your_house = np.array([14.0, 24.0, 14.25, 9.0])

In [ ]:
# my_house greater than or equal to 18
print(my_house >= 18)

[ True  True False False]

In [ ]:
# my_house less than your_house
print(my_house < your_house)

[False  True  True False]

# Logical Operators

In [ ]:
# Define variables
my_kitchen = 18.0
your_kitchen = 14.0

In [ ]:
# my_kitchen bigger than 10 and smaller than 18?
print(my_kitchen>10 and my_kitchen<18)

False

In [ ]:
# my_kitchen smaller than 14 or bigger than 17?
print(my_kitchen<14 or my_kitchen>17)

True

In [ ]:
# Double my_kitchen smaller than triple your_kitchen?
print(not(my_kitchen < your_kitchen))

True

In [ ]:
# Complex Situation
x = 8
y = 9
not(not(x < 3) and not(y > 14 or y > 10))

False

In [ ]:
# Create arrays
import numpy as np
my_marks = np.array([18.0, 20.0, 10.75, 9.50])

In [ ]:
# Boolean Array - Marks > 15
print(my_marks > 15)

[ True  True False False]

In [ ]:
# Using Boolean Array to filter
my_marks[my_marks > 15]

array([18., 20.])

In [ ]:
# Boolean Array with marks > 15 and marks < 20
print(my_marks[(my_marks > 15) & (my_marks < 20)])

[18.]

# if, elif and else

In [ ]:
# Declaring a Variable
points = 10

# Checking if point is greater than 25
if (points > 25):
    print("You have earned more than 25 points")

In [ ]:
# Checking if point is greater than 5
if (points > 5):
    print("You have earned more than 5 points")

You have earned more than 5 points

In [ ]:
# Declaring Variable
eggs = 8

# are eggs greater than 10 ?
if (eggs > 10):
    print("There are more than 10 eggs")

# are eggs greater than 5 ?
if (eggs > 5):
    print("There are more than 5 eggs")

There are more than 5 eggs

In [ ]:
# Declaring Variable
num = 12

# Nested ifs
if (num>6):
    print("num is greater than 6")
    if (num>20):
        print("num is greater than 20")
        if (num<25):
            print("num is less than 25")

num is greater than 6

In [ ]:
# Declaring Variable
num = 12

# if else Statement
if (num<6):
    print("num is greater than 6")
else:
    print("num is less than 6")

num is less than 6

In [ ]:
# if else Statement

if (1+1 == 2):
    print("True Statement")
else:
    print("False Statement")

True Statement

In [ ]:
# if else Statement

if (1+1 == 2):
    if (2+2 == 5):
        print("Yes")
    else:
        print("No")
else:
    print("We don't know")

No

In [ ]:
# if else elif
num = 5

if (num == 1):
    print("num is 1")
elif (num == 2):
    print("num is 2")
elif (num == 3):
    print("num is 3")
elif (num == 4):
    print("num is 4")
else:
    print("num is greater than 4")

num is greater than 4

In [ ]:
# Declare two variables
temperature = 25
is_sunny = True

# Use if, elif, else with logical operators
if (temperature > 30) and is_sunny:
    print("It's a hot and sunny day, perfect for the beach!")
elif (temperature <= 30) and is_sunny and not(temperature < 15):
    print("It's a pleasant and sunny day.")
elif (temperature < 15) or not is_sunny:
    print("It's a bit chilly or not sunny. Maybe wear a jacket.")
else:
    print("Weather conditions are a bit unusual today!")

It's a pleasant and sunny day.

# Filtering Pandas DataFrame

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
# Loading DataFrame from CSV
cars_df = pd.read_csv('https://raw.githubusercontent.com/HarisJafri-xcode/Python-Session-DataSets/refs/heads/main/Intermediate_Python/cars.csv')

In [ ]:
# Information about DataFrame
cars_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   country       7 non-null      object
 1   drives_right  7 non-null      bool
 2   cars_per_cap  7 non-null      int64
dtypes: bool(1), int64(1), object(1)
memory usage: 251.0+ bytes

In [ ]:
# View df
cars_df

         country  drives_right  cars_per_cap
0  United States          True           809
1      Australia         False           731
2          Japan         False           588
3          India         False            18
4         Russia          True           200
5        Morocco          True            70
6          Egypt          True            45

In [ ]:
# cars_per_cap Data Series
cars_df["cars_per_cap"]

0    809
1    731
2    588
3     18
4    200
5     70
6     45
Name: cars_per_cap, dtype: int64

In [ ]:
# cars_per_cap greater than 100
cars_df["cars_per_cap"] > 100

0     True
1     True
2     True
3    False
4     True
5    False
6    False
Name: cars_per_cap, dtype: bool

In [ ]:
# Storing Boolean DS
mask = cars_df["cars_per_cap"] > 100

# Rows where cars_per_cap is greater than 100
cars_df[mask]

         country  drives_right  cars_per_cap
0  United States          True           809
1      Australia         False           731
2          Japan         False           588
4         Russia          True           200

In [ ]:
# cpc > 100
cpc_mask = cars_df["cars_per_cap"] > 100

# drives right
drive_mask = cars_df["drives_right"] == True

# Subset
cars_df[cpc_mask | drive_mask]

         country  drives_right  cars_per_cap
0  United States          True           809
1      Australia         False           731
2          Japan         False           588
4         Russia          True           200
5        Morocco          True            70
6          Egypt          True            45

In [ ]:
# Subset
cars_df[cpc_mask & drive_mask]

         country  drives_right  cars_per_cap
0  United States          True           809
4         Russia          True           200