<a href="https://colab.research.google.com/github/HarisJafri-xcode/Data-Analyst-in-Python/blob/main/Loops.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# while Loop

In [ ]:
# Declaring Error
error = 100
threshold = 50

# Show Warning until Error is below Threshold
while error > threshold:
    print("Warning")
    error = error - 20
print("No Need to Worry")

Warning
Warning
Warning
No Need to Worry

# for Loop

In [ ]:
# String
name = "Haris"

# Using Index
print(name[0])
print(name[1])
print(name[2])
print(name[3])
print(name[4])

H
a
r
i
s

In [ ]:
# for Loop
for char in name:
    print(char)

H
a
r
i
s

In [ ]:
# List
age = [12, 13, 11]

# for Loop
for num in age:
    print(num)

12
13
11

In [ ]:
# Family Age
ages = [12, 13, 11]

# for Loop
for index, age in enumerate(ages):
    print("Person", index+1, "shall be", age+2, "years old after 2 Years")

Person 1 shall be 14 years old after 2 Years
Person 2 shall be 15 years old after 2 Years
Person 3 shall be 13 years old after 2 Years

In [ ]:
# house list of lists
house = [["hallway", 11.25],
         ["kitchen", 18.0],
         ["living room", 20.0],
         ["bedroom", 10.75],
         ["bathroom", 9.50]]

# Build a for loop from scratch
for x in house:
    print("the", x[0], "is", x[1], "sqm")

the hallway is 11.25 sqm
the kitchen is 18.0 sqm
the living room is 20.0 sqm
the bedroom is 10.75 sqm
the bathroom is 9.5 sqm

# Loops with other Data Structures

In [ ]:
# Definition of dictionary
europe = {'spain':'madrid', 'france':'paris', 'germany':'berlin',
          'norway':'oslo', 'italy':'rome', 'poland':'warsaw', 'austria':'vienna' }

In [ ]:
# Using Loop
for key, value in europe.items():
    print("Capital of", key.capitalize() , "is", value.capitalize())

Capital of Spain is Madrid
Capital of France is Paris
Capital of Germany is Berlin
Capital of Norway is Oslo
Capital of Italy is Rome
Capital of Poland is Warsaw
Capital of Austria is Vienna

In [ ]:
import numpy as np

In [ ]:
# 2D NumPy Array
numbers = np.array([[12, 25 ,13], [7, 18, 9]])

In [ ]:
# Iteration
for n in numbers:
    print(n)

[12 25 13]
[ 7 18  9]

In [ ]:
# Iteration
for n in np.nditer(numbers):
    print(n)

12
25
13
7
18
9

In [ ]:
import pandas as pd

In [ ]:
cars_df = pd.read_csv('https://raw.githubusercontent.com/HarisJafri-xcode/Python-Session-DataSets/refs/heads/main/Intermediate_Python/cars.csv')

In [ ]:
# applying for Loop
for c in cars_df:
    print(c)

country
drives_right
cars_per_cap

In [ ]:
# Current Pandas Dataframe
cars_df

         country  drives_right  cars_per_cap
0  United States          True           809
1      Australia         False           731
2          Japan         False           588
3          India         False            18
4         Russia          True           200
5        Morocco          True            70
6          Egypt          True            45

In [ ]:
# Adding a New Column
cars_df["check_column"] = True

In [ ]:
# Revised Pandas DF
cars_df

         country  drives_right  cars_per_cap  check_column
0  United States          True           809          True
1      Australia         False           731          True
2          Japan         False           588          True
3          India         False            18          True
4         Russia          True           200          True
5        Morocco          True            70          True
6          Egypt          True            45          True

In [ ]:
# deleting a Column
del cars_df["check_column"]

In [ ]:
# Checking again after Column deletion
cars_df

         country  drives_right  cars_per_cap
0  United States          True           809
1      Australia         False           731
2          Japan         False           588
3          India         False            18
4         Russia          True           200
5        Morocco          True            70
6          Egypt          True            45

In [ ]:
# Creating a Column to identify high cars_per_cap countries
cars_df["high_cars_per_cap"] = cars_df["cars_per_cap"] > 200

In [ ]:
# df after column addition
cars_df

         country  drives_right  cars_per_cap  high_cars_per_cap
0  United States          True           809               True
1      Australia         False           731               True
2          Japan         False           588               True
3          India         False            18              False
4         Russia          True           200              False
5        Morocco          True            70              False
6          Egypt          True            45              False

In [ ]:
# Using .iloc to extract first three rows of country column
cars_df["country"].iloc[0:3]

0    United States
1        Australia
2            Japan
Name: country, dtype: object

In [ ]:
# Using .loc to extract first three rows of country column
cars_df.loc[0:2, "country"]

0    United States
1        Australia
2            Japan
Name: country, dtype: object

In [ ]:
# iterating over each row individually
for index, row in cars_df.iterrows():
    print(index)
    print(row)

0
country              United States
drives_right                  True
cars_per_cap                   809
high_cars_per_cap             True
Name: 0, dtype: object
1
country              Australia
drives_right             False
cars_per_cap               731
high_cars_per_cap         True
Name: 1, dtype: object
2
country              Japan
drives_right         False
cars_per_cap           588
high_cars_per_cap     True
Name: 2, dtype: object
3
country              India
drives_right         False
cars_per_cap            18
high_cars_per_cap    False
Name: 3, dtype: object
4
country              Russia
drives_right           True
cars_per_cap            200
high_cars_per_cap     False
Name: 4, dtype: object
5
country              Morocco
drives_right            True
cars_per_cap              70
high_cars_per_cap      False
Name: 5, dtype: object
6
country              Egypt
drives_right          True
cars_per_cap            45
high_cars_per_cap    False
Name: 6, dtype: object

In [ ]:
# Creating a new Column
cars_df["country_code"] = ""

In [ ]:
# Filling Country Code
for index, row in cars_df.iterrows():
    cars_df.loc[index, "country_code"] = cars_df.loc[index, "country"][:2]

In [ ]:
# Observing df
cars_df

         country  drives_right  cars_per_cap  high_cars_per_cap country_code
0  United States          True           809               True           Un
1      Australia         False           731               True           Au
2          Japan         False           588               True           Ja
3          India         False            18              False           In
4         Russia          True           200              False           Ru
5        Morocco          True            70              False           Mo
6          Egypt          True            45              False           Eg